In [13]:
import numpy as np
import math
a1 = [[1,2,3]]
a2 = [[4,5,6]]
a1= np.array(a1).T
a2= np.array(a2).T
data = np.append(a1,a2,axis = 1)
data = np.append(data,a2,axis = 1)
print(data)

[[1 4 4]
 [2 5 5]
 [3 6 6]]


In [8]:
import numpy as np
import math
a1 = [[1,2,3],[7,8,9]]
a1 = np.array(a1)
a2 = [[4,5,6],[10,11,12]]
a2 = np.array(a2)
# print(a1[:,0])
a1= np.array([a1[:,0]]).T
a2= np.array([a2[:,0]]).T
data = np.append(a1,a2,axis = 1)
# data = np.append(data,a2,axis = 1)
print(data)

[[ 1  4]
 [ 7 10]]


In [20]:
import serial
import csv
import time
import pandas as pd
from datetime import datetime, timedelta
from time import sleep
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import math
from scipy import signal
from PIL import Image

data = './IOBB/All_Data/腳_fft.csv'

data = np.array(pd.read_csv(data))
pandasData={"Xg":data[:,1],"Yg":data[:,2],"Zg":data[:,3],"Xm":data[:,4],"Ym":data[:,5],"Zm":data[:,6]}
pandasData1 = {"ZZZ":data[1,:]}
# df = pd.DataFrame(pandasData)
df1 = pd.DataFrame(pandasData1)
df1

ZZZ
0  1.000000
1  2.617281
2  2.532655
3  0.361685
4 -0.278278
5 -0.353545
6  2.789207